### ISSUE TITLE
Configuration properties should have proper description and metadata

### ISSUE THREAD

**Issue by snicoll** [arangodb/spring-boot-starter#1]
To help users discover how to customize the auto-configurations offered by this starter, proper field level javadoc should be added for each property and the `spring-boot-configuraton-processor` should be enabled to generate a metadata file that can be read by the IDE.

The processor can also extract the default value if the field property is initialized (rather than doing it in the constructor).

Please review [the official documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-annotation-processor).

**Comment by mpv1989** [comment]
@snicoll Thanks for the feedback.
@hkernbach I created a PR #4 for this

**Comment by mpv1989** [comment]
PR merged
