### ISSUE TITLE
Update usage of deprecated Spring framework class

### ISSUE THREAD

**Issue by oliverlockwood** [arangodb/spring-boot-starter#11]
The `ArangoHealthIndicatorAutoConfiguration` class references `HealthIndicatorAutoConfiguration`.

As per the Javadoc for this class, it is:
```
 * @deprecated since 2.2.0 in favor of {@link HealthContributorAutoConfiguration}
```

**Comment by rashtao** [comment]
Thanks for reporting, fixed by https://github.com/arangodb/spring-boot-starter/commit/504cbe7b88e47999eddf226ee7afaa86cc4f486a
