### ISSUE TITLE
bump support to arangodb-spring-data 3.6.0

### ISSUE THREAD

**Issue by bwgjoseph** [arangodb/spring-boot-starter#14]
Hi,

Possible to release new version that brings in `arangodb-spring-data 3.6.0`?

There are couple of nice fixes from `3.30 > 3.6.0` and the current starter is not updated

Thanks!

**Comment by rashtao** [comment]
Thanks for reporting, here are new releases containing `arangodb-spring-data` `3.7.0`:
- https://github.com/arangodb/spring-boot-starter/releases/tag/v2.4-0
- https://github.com/arangodb/spring-boot-starter/releases/tag/v2.5-0
- https://github.com/arangodb/spring-boot-starter/releases/tag/v2.6-0
