### ISSUE TITLE
Consider making the dependency to actuator optional

### ISSUE THREAD

**Issue by snicoll** [arangodb/spring-boot-starter#2]
It is a bit unusual that a starter brings a hard dependency on the actuator. Rather it should guard auto-configurations to the presence of the relevant classes and kick in only if necessary. 

If the actuator is an optional feature, it should be flagged as such in the dependencies.

**Comment by mpv1989** [comment]
@snicoll Thanks for the feedback.
@hkernbach I created a PR #3  for this

**Comment by mpv1989** [comment]
PR merged
