### ISSUE TITLE
Support Spring Boot 3

### ISSUE THREAD

**Issue by aburmeis** [arangodb/spring-boot-starter#20]
As soon as arangodb/spring-data#250 is solved, the boot starter has to be updated to support Spring Boot 3 and Java Driver 7

**Comment by rashtao** [comment]
Sorry @aburmeis ,
I created https://github.com/arangodb/spring-boot-starter/pull/21 and realized only now that you already had some work in progress about this!

Feel free to review and suggest changes if needed.

**Comment by aburmeis** [comment]
@rashtao added my thought on the PR
