### ISSUE TITLE
using springboot 3.2.4 and arango-spring-data 4.1.0 causes my application failed to get started, there is bean creation issue with "arangoTemplate"

### ISSUE THREAD

**Issue by sushmalpu** [arangodb/spring-boot-starter#27]
[TenantArangoTemplateConfiguration.txt](https://github.com/user-attachments/files/15613012/TenantArangoTemplateConfiguration.txt)
[ServiceArangoTemplateConfiguration.txt](https://github.com/user-attachments/files/15613014/ServiceArangoTemplateConfiguration.txt)
Hi,
I am using Springboot version : 3.2.4 and arangodb-spring-data: 4.1.0 and creating dbaas-client lib with below classes

using **ArangoConfiguration** Interface to make class **ServiceArangoTemplateConfiguration** like below which have overriding bean

**public class ServiceArangoTemplateConfiguration implements ArangoConfiguration {
@Override
    @Primary
    @Bean(name = {"dbaasServiceArangoTemplate", "arangoTemplate"})
    public ArangoOperations arangoTemplate() throws Exception {
        return new DbaasArangoTemplate(serviceArangoDatabaseProvider, arangoConverter(), resolverFactory(), dbaasArangoConfig);
    }
  }**

and further creating other **TenantArangoTemplateConfiguration** which extending **ServiceArangoTemplateConfiguration** like below which having other bean defined 

**public class **TenantArangoTemplateConfiguration** extends **ServiceArangoTemplateConfiguration** {
@Bean(TENANT_ARANGO_TEMPLATE)
    @ConditionalOnMissingBean(name = "dbaasTenantArangoTemplate")
    public ArangoOperations tenantArangoTemplate() throws Exception {
        return new DbaasArangoTemplate(tenantArangoDatabaseProvider, arangoConverter(), resolverFactory(), dbaasArangoConfig);
    }
}**

so the issue is when I am using this **TenantArangoTemplateConfiguration** defined inside annoattion **EnableTenantDbaasArangoDB**  to my springboot app demo 
**@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Import({TenantArangoTemplateConfiguration.class})
public @interface EnableTenantDbaasArangoDB {

}**
 I am getting issue that :  **org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'arangoTemplate' defined in class path resource [com/helloworld/cloud/dbaas/client/arangodb/configuration/TenantArangoTemplateConfiguration.class]: No matching factory method found on class [com.helloworld.cloud.dbaas.client.arangodb.configuration.TenantArangoTemplateConfiguration]: factory bean 'com.helloworld.cloud.dbaas.client.arangodb.configuration.TenantArangoTemplateConfiguration'; factory method 'arangoTemplate()'. Check that a method with the specified name exists and that it is non-static**.

My demo project configuration:

@Configuration
@Profile("prod")
@EnableTenantDbaasArangoDB
@Slf4j
public class DbaasArangoConfig {

    @Autowired
    private DbaasHelper dbaasHelper;
    @Bean("sourceArangoTemplate")
    ArangoDatabase arangoTemplate(DatabasePool databasePool) {
        try {
            ArangoDatabaseProvider arangoDatabaseProvider = new ArangoDatabaseProvider(databasePool, dbaasHelper.getArangoClassifierBuilder(), dbaasHelper.getDataBaseConfig("arango"));
            return arangoDatabaseProvider.provide();
        } catch (Exception e) {
            log.error("Cannot create Arango database", e);
        }
        return null;
    }

}

Earlier I was using springboot 2 and this logic working fine in demo project, but when dbaas-client lib updated with springboot 3 , I updated demo to 3.2.4 and its starting giving this error
```

**Comment by rashtao** [comment]
Have you tried keeping the same bean name `arangoTemplate` and setting `dbaasServiceArangoTemplate` as alias? I.e.:

```
// ...

@Override
@Primary
@Bean(name = {"arangoTemplate", "dbaasServiceArangoTemplate"})
public ArangoOperations arangoTemplate() throws Exception {
    return new DbaasArangoTemplate(serviceArangoDatabaseProvider, arangoConverter(), resolverFactory(), dbaasArangoConfig);
}

// ...
```
