### ISSUE TITLE
Move configuration properties prefix to a dedicated namespace

### ISSUE THREAD

**Issue by snicoll** [arangodb/spring-boot-starter#9]
Thank you for your work on the starter. As [documented in the reference guide](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-configuration-keys) we prefer that third party starters do not use our configuration namespace.

Can you please rename those `spring.data.arangodb.*` in `ArangoProperties`? A root `arangodb.*` sounds good.

Thanks!

**Comment by rashtao** [comment]
@snicoll thanks for pointing this out!
fixed in https://github.com/arangodb/spring-boot-starter/commit/4cfa6fdb5d81f2a7f56f64dbdcff2d91837c155d
